### ISSUE TITLE
037-iob-pips fails on Zynq

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/prjxray#1042]
There is a Zynq-related failure in CI of the 037-iob-pips fuzzer:

```
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m: + echo '`define SEED 32'\''h1772015f'
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m: + make -f /tmpfs/src/github/symbiflow-prjxray-presubmit-db-zynq7/utils/top_generate.mk
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m: Traceback (most recent call last):
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m:   File "/tmpfs/src/github/symbiflow-prjxray-presubmit-db-zynq7/utils/bit2fasm.py", line 116, in <module>
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m:     main()
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m:   File "/tmpfs/src/github/symbiflow-prjxray-presubmit-db-zynq7/utils/bit2fasm.py", line 112, in main
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m:     args.db_root, bits_file.name, args.verbose, args.canonical)
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m:   File "/tmpfs/src/github/symbiflow-prjxray-presubmit-db-zynq7/utils/bit2fasm.py", line 41, in bits_to_fasm
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m:     sort_key=grid.tile_key,
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m:   File "/tmpfs/src/github/symbiflow-prjxray-presubmit-db-zynq7/third_party/fasm/fasm/output.py", line 376, in merge_and_sort
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m:     for line in model:
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m:   File "/tmpfs/src/github/symbiflow-prjxray-presubmit-db-zynq7/prjxray/fasm_disassembler.py", line 121, in find_features_in_bitstream
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m:     solved_bitdata, bitdata, verbose=verbose):
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m:   File "/tmpfs/src/github/symbiflow-prjxray-presubmit-db-zynq7/prjxray/fasm_disassembler.py", line 51, in find_features_in_tile
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m:     tile_segbits = self.grid.get_tile_segbits_at_tilename(tile_name)
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m:   File "/tmpfs/src/github/symbiflow-prjxray-presubmit-db-zynq7/prjxray/grid.py", line 117, in get_tile_segbits_at_tilename
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m:     return self.db.get_tile_segbits(gridinfo.tile_type)
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m:   File "/tmpfs/src/github/symbiflow-prjxray-presubmit-db-zynq7/prjxray/db.py", line 147, in get_tile_segbits
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m:     self.tile_types[tile_type.upper()])
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m:   File "/tmpfs/src/github/symbiflow-prjxray-presubmit-db-zynq7/prjxray/tile_segbits.py", line 80, in __init__
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m:     self.segbits[BlockType.CLB_IO_CLK] = read_segbits(f)
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m:   File "/tmpfs/src/github/symbiflow-prjxray-presubmit-db-zynq7/prjxray/tile_segbits.py", line 61, in read_segbits
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m:     assert len(parts) > 1
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m: AssertionError
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m: make[3]: *** [design_bits.ok] Error 1
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m: make[2]: *** [build/11/specimen_016/OK] Error 2
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m: make[2]: *** Waiting for unfinished jobs....
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m: make[1]: *** [run] Error 2
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m: 
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m: --------------------------------------------------------------------------
2019-09-05T01:28:36.873819 - 037-iob-pips             - 2h18m: Failed @ 2019-09-05T01:28:36.620851 with exit code: 2
2019-09-05T01:28:36.969721 - 037-iob-pips             - 2h18m: WARNING: Fuzzer failed!
```

Happens here: https://github.com/SymbiFlow/prjxray/pull/1040

**Comment by tmichalak** [comment]
Haven't seen this for a while, closing for now.
