### ISSUE TITLE
Read the docs build failing on prjxray?

### ISSUE THREAD

**Issue by litghost** [SymbiFlow/prjxray#1465]
I'm seeing the following failure on the "Read the docs" build:
```
ERROR: Exception:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/prjxray/envs/1447/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/prjxray/envs/1447/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/prjxray/envs/1447/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 379, in run
    requirement_set
  File "/home/docs/checkouts/readthedocs.org/user_builds/prjxray/envs/1447/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 191, in get_installation_order
    weights = get_topological_weights(graph)
  File "/home/docs/checkouts/readthedocs.org/user_builds/prjxray/envs/1447/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 242, in get_topological_weights
    assert len(weights) == len(graph)
AssertionError
```

Unclear to me what is happening here?  FYI @rw1nkler / @mithro / @acomodi

**Comment by litghost** [comment]
This has been fixed
