### ISSUE TITLE
TypeError in 074-dump_all/reduce_tile_types.py

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#147]
Using `Python 3.5.3` on Debian 9.5

```
100% (275 of 275) |##############################################################################################################################################################################################################################################################################################################################################################################| Elapsed Time: 0:00:00 ETA:  00:00:00
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "reduce_tile_types.py", line 205, in read_json5
    sites = tuple(get_sites(tile, node_lookup.site_pin_node_to_wires))
  File "reduce_tile_types.py", line 162, in get_sites
    site['site'] for site in tile['sites'])
  File "/big/github/SymbiFlow/prjxray/prjxray/lib.py", line 191, in find_origin_coordinate
    if len(site_names) == 0:
TypeError: object of type 'generator' has no len()
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "reduce_tile_types.py", line 333, in <module>
    main()
  File "reduce_tile_types.py", line 321, in main
    pool, site_types, tile_type, tiles[tile_type], node_lookup)
  File "reduce_tile_types.py", line 241, in reduce_tile
    new_wires) in enumerate(iter):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 314, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 695, in next
    raise value
TypeError: object of type 'generator' has no len()
```

**Comment by mcmasterg** [comment]
Sounds like this is fixed
