### ISSUE TITLE
fuzzer 052-clkin broken

### ISSUE THREAD

**Issue by mcmasterg** [SymbiFlow/prjxray#165]
possibly a regression of some recent cleanup

```
+ python3 ../generate.py
Loading artix7 grid.
Loading bits from design.bits.
Loading tags from design.txt.
Compiling segment data.
Traceback (most recent call last):
  File "../generate.py", line 66, in <module>
    segmk.write()
  File "/home/mcmaster/sf/prjxray/prjxray/segmaker.py", line 268, in write
    ]) != 0
AssertionError
Makefile:16: recipe for target 'specimen_001/OK' failed
make: *** [specimen_001/OK] Error 1
```

**Comment by mcmasterg** [comment]
Easy fix, the regression is actually not merged in yet. I'll push fix as part of PR

**Comment by mcmasterg** [comment]
Maybe? it actually has another issue

```
python3 maketodo.py > todo.txt
Traceback (most recent call last):
  File "maketodo.py", line 24, in <module>
    (os.getenv("XRAY_DATABASE_DIR"), os.getenv("XRAY_DATABASE")))
  File "maketodo.py", line 15, in maketodo
    todos.remove(line[0])
KeyError: 'INT_L.LH0.LH12'
Makefile:20: recipe for target 'todo.txt' failed
make: *** [todo.txt] Error 1
```

**Comment by mcmasterg** [comment]
057-bipips and 053-ctrlin are also broken like 052-clkin
