### ISSUE TITLE
installing requirements

### ISSUE THREAD

**Issue by GBrics** [SymbiFlow/prjxray#1693]
I carefully followed the steps described in the readme but I'm getting errors when trying to install all the requirements using : 
sudo -H pip3 install -r requirements.txt
(Option2 isn't working neither, modifications on pyjson5 didn't fix the issue)

Reported error : 

gaetan@gaetan-VirtualBox:~/xray/prjxray$ sudo -H pip3 install -r requirements.txt
Obtaining file:///home/gaetan/xray/prjxray/third_party/fasm (from -r requirements.txt (line 1))
Obtaining file:///home/gaetan/xray/prjxray/third_party/python-sdf-timing (from -r requirements.txt (line 2))
    Complete output from command python setup.py egg_info:
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    No local packages or download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/gaetan/xray/prjxray/third_party/python-sdf-timing/setup.py", line 37, in <module>
        'console_scripts': ['sdf_timing_parse=sdf_timing.sdfparse:main'],
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 657, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/gaetan/xray/prjxray/third_party/python-sdf-timing/

**Comment by GBrics** [comment]
Problem was coming from the python3 version. I did not manage to put a version of python higher than 3.7 as default on this version of ubuntu (16.04). Problem fixed by changing ubuntu version to a more recent one.
