### ISSUE TITLE
Zynq build failing but unclear why....

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#1796]
https://source.cloud.google.com/results/invocations/5af497f6-b3c8-442e-a394-c42f90a0b87e/log
```
2021-12-07T13:11:30 - xc7z020clg484-1/074-dump_all              - 4h25m: touch run.xc7z020clg484-1.ok
2021-12-07T13:11:30 - xc7z020clg484-1/074-dump_all              - 4h25m: make[2]: Leaving directory '/tmpfs/src/github/symbiflow-prjxray-continuous-db-zynq7/fuzzers/074-dump_all'
2021-12-07T13:11:30 - xc7z020clg484-1/074-dump_all              - 4h25m:
2021-12-07T13:11:30 - xc7z020clg484-1/074-dump_all              - 4h25m: --------------------------------------------------------------------------
2021-12-07T13:11:30 - xc7z020clg484-1/074-dump_all              - 4h25m: Succeeded! @ 2021-12-07T13:11:30.439403
make[1]: Leaving directory '/tmpfs/src/github/symbiflow-prjxray-continuous-db-zynq7/fuzzers'
Makefile:181: recipe for target 'db-zynq7' failed
make: *** [db-zynq7] Error 2
Script done, file is /tmpfs/tmp/tmp.xUCrtRhzC8
+ DATABASE_RET=2
+ set +x -e
Packing failing test cases
----------------------------------------
A failure occurred during Database build.
----------------------------------------
========================================
 Disk space in failure path
----------------------------------------
81G	.


[ID: 2955330] Build finished after 18322 secs, exit value: 2
```

**Comment by kgugala** [comment]
this is the cause:

```
34100 2021-12-07T09:23:37 - xc7z020clg484-1/030-iob                   - 48m50s: + make -f /tmpfs/src/github/symbiflow-prjxray-continuous-db-zynq7/utils/top_generate.mk^M
34101 2021-12-07T09:23:37 - xc7z020clg484-1/030-iob                   - 48m50s: Traceback (most recent call last):^M
34102 2021-12-07T09:23:37 - xc7z020clg484-1/030-iob                   - 48m50s:   File "/tmpfs/src/github/symbiflow-prjxray-continuous-db-zynq7/utils/dbfixup.py", line 745, in <module>^M
34103 2021-12-07T09:23:37 - xc7z020clg484-1/030-iob                   - 48m50s:     main()^M
34104 2021-12-07T09:23:37 - xc7z020clg484-1/030-iob                   - 48m50s:   File "/tmpfs/src/github/symbiflow-prjxray-continuous-db-zynq7/utils/dbfixup.py", line 733, in main^M
34105 2021-12-07T09:23:37 - xc7z020clg484-1/030-iob                   - 48m50s:     run(^M
34106 2021-12-07T09:23:37 - xc7z020clg484-1/030-iob                   - 48m50s:   File "/tmpfs/src/github/symbiflow-prjxray-continuous-db-zynq7/utils/dbfixup.py", line 697, in run^M
34107 2021-12-07T09:23:37 - xc7z020clg484-1/030-iob                   - 48m50s:     update_segs(^M
34108 2021-12-07T09:23:37 - xc7z020clg484-1/030-iob                   - 48m50s:   File "/tmpfs/src/github/symbiflow-prjxray-continuous-db-zynq7/utils/dbfixup.py", line 609, in update_segs^M
34109 2021-12-07T09:23:37 - xc7z020clg484-1/030-iob                   - 48m50s:     update_seg_fns(^M
34110 2021-12-07T09:23:37 - xc7z020clg484-1/030-iob                   - 48m50s:   File "/tmpfs/src/github/symbiflow-prjxray-continuous-db-zynq7/utils/dbfixup.py", line 521, in update_seg_fns^M
34111 2021-12-07T09:23:37 - xc7z020clg484-1/030-iob                   - 48m50s:     new_changes, lines = add_zero_bits(^M
34112 2021-12-07T09:23:37 - xc7z020clg484-1/030-iob                   - 48m50s:   File "/tmpfs/src/github/symbiflow-prjxray-continuous-db-zynq7/utils/dbfixup.py", line 256, in add_zero_bits^M
34113 2021-12-07T09:23:37 - xc7z020clg484-1/030-iob                   - 48m50s:     zero_groups.add_tag_bits(tag, bits)^M
34114 2021-12-07T09:23:37 - xc7z020clg484-1/030-iob                   - 48m50s:   File "/tmpfs/src/github/symbiflow-prjxray-continuous-db-zynq7/utils/dbfixup.py", line 153, in add_tag_bits^M
34115 2021-12-07T09:23:37 - xc7z020clg484-1/030-iob                   - 48m50s:     assert len(self.tag_to_groups[tag]) == 1^M
34116 2021-12-07T09:23:37 - xc7z020clg484-1/030-iob                   - 48m50s: AssertionError^M
34117 2021-12-07T09:23:37 - xc7z020clg484-1/030-iob                   - 48m50s: make[3]: *** [build/segbits_xiob33.db] Error 1^M
34118 2021-12-07T09:23:37 - xc7z020clg484-1/030-iob                   - 48m50s: make[2]: *** [run] Error 2^M
```
