### ISSUE TITLE
tiledata["grid_x"] - KeyError: 'grid_x'

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#190]
```
Generating for kintex7
--------------------------------------------
settings.sh 2daf6a69dd6d20df7b1273ff43c5c340abe36f8229d297646865edcfd91eff18  ./kintex7/settings.sh
export XRAY_DATABASE="kintex7"
export XRAY_PART="xc7k70tfbg676-2"
export XRAY_ROI="SLICE_X0Y50:SLICE_X19Y99 DSP48_X0Y20:DSP48_X0Y39 RAMB18_X0Y20:RAMB18_X0Y39 RAMB36_X0Y10:RAMB36_X0Y19"
export XRAY_ROI_FRAMES="0x00400100:0x004006ff"
export XRAY_ROI_GRID_X1="9"
export XRAY_ROI_GRID_X2="38"
export XRAY_ROI_GRID_Y1="104"
export XRAY_ROI_GRID_Y2="156"
# Choose the first N High Range I/Os
export XRAY_PIN_00="K25"
export XRAY_PIN_01="K26"
export XRAY_PIN_02="L24"
export XRAY_PIN_03="L25"
export XRAY_PIN_04="M19"
export XRAY_PIN_05="M20"
export XRAY_PIN_06="M21"
source $(dirname ${BASH_SOURCE[0]})/../../utils/environment.sh
--------------------------------------------
Loading tilegrid.
Writing ./html/kintex7/index.html
Traceback (most recent call last):
  File "/tmp/tmp.Hwof25Y0xQ/prjxray/htmlgen/htmlgen.py", line 981, in <module>
    main()
  File "/tmp/tmp.Hwof25Y0xQ/prjxray/htmlgen/htmlgen.py", line 977, in main
    run(settings=args.settings, output=args.output, verbose=args.verbose)
  File "/tmp/tmp.Hwof25Y0xQ/prjxray/htmlgen/htmlgen.py", line 956, in run
    mk_tilegrid_page(dbstate, output, grid)
  File "/tmp/tmp.Hwof25Y0xQ/prjxray/htmlgen/htmlgen.py", line 367, in mk_tilegrid_page
    grid_map, grid_range = place_tiles(grid)
  File "/tmp/tmp.Hwof25Y0xQ/prjxray/htmlgen/htmlgen.py", line 268, in place_tiles
    grid_x = tiledata["grid_x"]
KeyError: 'grid_x'
The command "./.travis/generate-html.sh" exited with 1.
```

**Comment by mithro** [comment]
This looks like it's being caused by the kintex7 database being out of date.

**Comment by mithro** [comment]
Fixed in https://github.com/SymbiFlow/prjxray-db/commit/e1da32c1ceaa7e7070fcde13340ed6cac3153912
