### ISSUE TITLE
Fuzzer issues

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#239]
```
/big/github/SymbiFlow/prjxray-kintex/build/tools/segmatch -o build/segbits_clbx.rdb build/specimen_001/segdata_clbl[lm]_[lr].txt
Reading build/specimen_001/segdata_clbll_l.txt.
Reading build/specimen_001/segdata_clbll_r.txt.
Reading build/specimen_001/segdata_clblm_l.txt.
Reading build/specimen_001/segdata_clblm_r.txt.
#of segments: 498
#of bits: 2069
#of tags: 38
#of const0 tags: 0
#of const1 tags: 0
min #of candidates: 1
max #of candidates: 1
avg #of candidates: 1.000
cp build/segbits_clbx.rdb build/segbits_clbx.db
make[2]: Leaving directory '/big/github/SymbiFlow/prjxray-kintex/fuzzers/011-ffconfig'
make pushdb
make[2]: Entering directory '/big/github/SymbiFlow/prjxray-kintex/fuzzers/011-ffconfig'
bash /big/github/SymbiFlow/prjxray-kintex/utils/mergedb.sh clbll_l build/segbits_clblx.db
+ test 2 = 2
+ test -e build/segbits_clblx.db
../clb.mk:19: recipe for target 'pushdb' failed
make[2]: *** [pushdb] Error 1
make[2]: Leaving directory '/big/github/SymbiFlow/prjxray-kintex/fuzzers/011-ffconfig'
../fuzzer.mk:13: recipe for target 'run' failed
make[1]: *** [run] Error 2
make[1]: Leaving directory '/big/github/SymbiFlow/prjxray-kintex/fuzzers/011-ffconfig'
Makefile:12: recipe for target '011-ffconfig/run.ok' failed
make: *** [011-ffconfig/run.ok] Error 2
```

**Comment by mithro** [comment]
Going to give this a try;
```patch
diff --git a/fuzzers/clb.mk b/fuzzers/clb.mk
index 4652ff4..2bc1456 100644
--- a/fuzzers/clb.mk
+++ b/fuzzers/clb.mk
@@ -17,10 +17,10 @@ endif

 pushdb:
        $(DBFIXUP)
-       ${XRAY_MERGEDB} clbll_l build/segbits_clblx.db
-       ${XRAY_MERGEDB} clbll_r build/segbits_clblx.db
-       ${XRAY_MERGEDB} clblm_l build/segbits_clblx.db
-       ${XRAY_MERGEDB} clblm_r build/segbits_clblx.db
+       ${XRAY_MERGEDB} clbll_l build/segbits_clbx.db
+       ${XRAY_MERGEDB} clbll_r build/segbits_clbx.db
+       ${XRAY_MERGEDB} clblm_l build/segbits_clbx.db
+       ${XRAY_MERGEDB} clblm_r build/segbits_clbx.db

 .PHONY: database pushdb

```

**Comment by mithro** [comment]
Alternative patch could be;
```patch
diff --git a/fuzzers/clb.mk b/fuzzers/clb.mk
index 4652ff4..d806e12 100644
--- a/fuzzers/clb.mk
+++ b/fuzzers/clb.mk
@@ -3,12 +3,12 @@ DBFIXUP ?=

 include ../fuzzer.mk

-database: build/segbits_clbx.db
+database: build/segbits_clblx.db

 build/segbits_clbx.rdb: $(SPECIMENS_OK)
-       ${XRAY_SEGMATCH} -o build/segbits_clbx.rdb $(addsuffix /segdata_clbl[lm]_[lr].txt,$(SPECIMENS))
+       ${XRAY_SEGMATCH} -o build/segbits_clblx.rdb $(addsuffix /segdata_clbl[lm]_[lr].txt,$(SPECIMENS))

-build/segbits_clbx.db: build/segbits_clbx.rdb
+build/segbits_clblx.db: build/segbits_clblx.rdb
 ifeq ($(CLB_DBFIXUP),Y)
        ${XRAY_DBFIXUP} --db_root build --zero-db bits.dbf --seg-fn-in $^ --seg-fn-out $@
 else
```

**Comment by mithro** [comment]
After using the second patch, I get the following?
```
Writing segdata_hclk_gtx.txt.
Writing segdata_int_interface_r.txt.
Writing segdata_cfg_center_bot.txt.
Writing segdata_hclk_clb.txt.
Writing segdata_cmt_top_l_lower_b.txt.
Writing segdata_rioi_tbytesrc.txt.
touch build/specimen_001/OK
/big/github/SymbiFlow/prjxray-kintex/build/tools/segmatch -o build/segbits_clblx.rdb build/specimen_001/segdata_clbl[lm]_[lr].txt
Reading build/specimen_001/segdata_clbll_l.txt.
Reading build/specimen_001/segdata_clbll_r.txt.
Reading build/specimen_001/segdata_clblm_l.txt.
Reading build/specimen_001/segdata_clblm_r.txt.
#of segments: 200
#of bits: 38
#of tags: 46
#of const0 tags: 8
#of const1 tags: 0
min #of candidates: 1
max #of candidates: 2
avg #of candidates: 1.579
python3 /big/github/SymbiFlow/prjxray-kintex/utils/dbfixup.py --db_root build --zero-db bits.dbf --seg-fn-in build/segbits_clblx.rdb --seg-fn-out build/segbits_clblx.db
CLB INT mode: False
Segbit groups: 8
Traceback (most recent call last):
  File "/big/github/SymbiFlow/prjxray-kintex/utils/dbfixup.py", line 327, in <module>
    main()
  File "/big/github/SymbiFlow/prjxray-kintex/utils/dbfixup.py", line 323, in main
    args.seg_fn_out, args.verbose)
  File "/big/github/SymbiFlow/prjxray-kintex/utils/dbfixup.py", line 302, in run
    verbose=verbose)
  File "/big/github/SymbiFlow/prjxray-kintex/utils/dbfixup.py", line 284, in update_segs
    update_seg_fns(fn_inouts, zero_db, clb_int, lazy=lazy, verbose=verbose)
  File "/big/github/SymbiFlow/prjxray-kintex/utils/dbfixup.py", line 223, in update_seg_fns
    fn_in, fn_out, zero_db, clb_int=clb_int, verbose=verbose)
  File "/big/github/SymbiFlow/prjxray-kintex/utils/dbfixup.py", line 139, in add_zero_bits
    "<const0>", "<const1>"), "Entries must be resolved"
AssertionError: Entries must be resolved
../clb.mk:13: recipe for target 'build/segbits_clblx.db' failed
make[2]: *** [build/segbits_clblx.db] Error 1
make[2]: Leaving directory '/big/github/SymbiFlow/prjxray-kintex/fuzzers/016-clbnoutmux'
../fuzzer.mk:13: recipe for target 'run' failed
make[1]: *** [run] Error 2
make[1]: Leaving directory '/big/github/SymbiFlow/prjxray-kintex/fuzzers/016-clbnoutmux'
Makefile:17: recipe for target '016-clbnoutmux/run.ok' failed
make: *** [016-clbnoutmux/run.ok] Error 2
```

**Comment by mithro** [comment]
Looks to be related to https://github.com/SymbiFlow/prjxray/commit/656fde07c1ed0f735e858609c9a0fecafa902fb1 ?

**Comment by mithro** [comment]
Added the following;
```patch
diff --git a/utils/dbfixup.py b/utils/dbfixup.py
index 3e70999..c6edbb0 100755
--- a/utils/dbfixup.py
+++ b/utils/dbfixup.py
@@ -136,7 +136,7 @@ def add_zero_bits(fn_in, fn_out, zero_db, clb_int=False, verbose=False):

             tag, bits, mode = parse_line(line)
             assert mode not in (
-                "<const0>", "<const1>"), "Entries must be resolved"
+                "<const0>", "<const1>"), "Entries must be resolved. tag:%s, bits:%s, mode:%s" % (tag, bits, mode)
             if mode:
                 assert mode == "<0 candidates>"
             """
```
and now get;
```
/big/github/SymbiFlow/prjxray-kintex/build/tools/segmatch -o build/segbits_clblx.rdb build/specimen_001/segdata_clbl[lm]_[lr].txt
Reading build/specimen_001/segdata_clbll_l.txt.
Reading build/specimen_001/segdata_clbll_r.txt.
Reading build/specimen_001/segdata_clblm_l.txt.
Reading build/specimen_001/segdata_clblm_r.txt.
#of segments: 200
#of bits: 38
#of tags: 46
#of const0 tags: 8
#of const1 tags: 0
min #of candidates: 1
max #of candidates: 2
avg #of candidates: 1.579
python3 /big/github/SymbiFlow/prjxray-kintex/utils/dbfixup.py --db_root build --zero-db bits.dbf --seg-fn-in build/segbits_clblx.rdb --seg-fn-out build/segbits_clblx.db
CLB INT mode: False
Segbit groups: 8
Traceback (most recent call last):
  File "/big/github/SymbiFlow/prjxray-kintex/utils/dbfixup.py", line 327, in <module>
    main()
  File "/big/github/SymbiFlow/prjxray-kintex/utils/dbfixup.py", line 323, in main
    args.seg_fn_out, args.verbose)
  File "/big/github/SymbiFlow/prjxray-kintex/utils/dbfixup.py", line 302, in run
    verbose=verbose)
  File "/big/github/SymbiFlow/prjxray-kintex/utils/dbfixup.py", line 284, in update_segs
    update_seg_fns(fn_inouts, zero_db, clb_int, lazy=lazy, verbose=verbose)
  File "/big/github/SymbiFlow/prjxray-kintex/utils/dbfixup.py", line 223, in update_seg_fns
    fn_in, fn_out, zero_db, clb_int=clb_int, verbose=verbose)
  File "/big/github/SymbiFlow/prjxray-kintex/utils/dbfixup.py", line 139, in add_zero_bits
    "<const0>", "<const1>"), "Entries must be resolved. tag:%s, bits:%s, mode:%s" % (tag, bits, mode)
AssertionError: Entries must be resolved. tag:CLB.SLICE_X0.AOUTMUX.O6, bits:set(), mode:<const0>
../clb.mk:13: recipe for target 'build/segbits_clblx.db' failed
make[2]: *** [build/segbits_clblx.db] Error 1
make[2]: Leaving directory '/big/github/SymbiFlow/prjxray-kintex/fuzzers/016-clbnoutmux'
../fuzzer.mk:13: recipe for target 'run' failed
make[1]: *** [run] Error 2
make[1]: Leaving directory '/big/github/SymbiFlow/prjxray-kintex/fuzzers/016-clbnoutmux'
Makefile:17: recipe for target '016-clbnoutmux/run.ok' failed
make: *** [016-clbnoutmux/run.ok] Error 2
```

**Comment by JohnDMcMaster** [comment]
hmm I thought this was covered. Will review tomorrow

**Comment by mcmasterg** [comment]
I believe both mentioned issues should have fixes / workarounds merged
