### ISSUE TITLE
AssertionError: Invalid tag name: bit, line: bit 00_00

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#258]
```
make[2]: Leaving directory '/big/github/SymbiFlow/prjxray/fuzzers/050-intpips'
make pushdb
make[2]: Entering directory '/big/github/SymbiFlow/prjxray/fuzzers/050-intpips'
python3 /big/github/SymbiFlow/prjxray/utils/dbfixup.py --db-root . --clb-int
CLB INT mode: True
Segbit groups: 6
Segbit: checked 0 files w/ 0 changed lines
Mask: checked files
bash /big/github/SymbiFlow/prjxray/utils/mergedb.sh int_l seg_int_l.segbits
+ test 2 = 2
+ test -e seg_int_l.segbits
++ mktemp -p .
+ tmp1=./tmp.bNQLRfNaP7
++ mktemp -p .
+ tmp2=./tmp.jH9TjoD4Ri
+ db=/big/github/SymbiFlow/prjxray/database/artix7/segbits_int_l.db
+ case "$1" in
+ sed -e 's/^INT\./INT_L./'
+ touch /big/github/SymbiFlow/prjxray/database/artix7/segbits_int_l.db
+ sort -u ./tmp.bNQLRfNaP7 /big/github/SymbiFlow/prjxray/database/artix7/segbits_int_l.db
+ grep -v '<.*>'
+ python3 /big/github/SymbiFlow/prjxray/utils/parsedb.py --strict ./tmp.jH9TjoD4Ri /big/github/SymbiFlow/prjxray/database/artix7/segbits_int_l.db
+ rm -f ./tmp.bNQLRfNaP7
bash /big/github/SymbiFlow/prjxray/utils/mergedb.sh int_r seg_int_r.segbits
+ test 2 = 2
+ test -e seg_int_r.segbits
++ mktemp -p .
+ tmp1=./tmp.yCjFti6iIy
++ mktemp -p .
+ tmp2=./tmp.K6pu6duyOS
+ db=/big/github/SymbiFlow/prjxray/database/artix7/segbits_int_r.db
+ case "$1" in
+ sed -e 's/^INT\./INT_R./'
+ touch /big/github/SymbiFlow/prjxray/database/artix7/segbits_int_r.db
+ sort -u ./tmp.yCjFti6iIy /big/github/SymbiFlow/prjxray/database/artix7/segbits_int_r.db
+ grep -v '<.*>'
+ python3 /big/github/SymbiFlow/prjxray/utils/parsedb.py --strict ./tmp.K6pu6duyOS /big/github/SymbiFlow/prjxray/database/artix7/segbits_int_r.db
+ rm -f ./tmp.yCjFti6iIy
bash /big/github/SymbiFlow/prjxray/utils/mergedb.sh mask_clbll_l mask_clbll_l.segbits
+ test 2 = 2
+ test -e mask_clbll_l.segbits
++ mktemp -p .
+ tmp1=./tmp.RbTrzx1Df9
++ mktemp -p .
+ tmp2=./tmp.RNzWhsDeE5
+ db=/big/github/SymbiFlow/prjxray/database/artix7/segbits_mask_clbll_l.db
+ case "$1" in
+ db=/big/github/SymbiFlow/prjxray/database/artix7/mask_clbll_l.db
+ cp mask_clbll_l.segbits ./tmp.RbTrzx1Df9
+ touch /big/github/SymbiFlow/prjxray/database/artix7/mask_clbll_l.db
+ sort -u ./tmp.RbTrzx1Df9 /big/github/SymbiFlow/prjxray/database/artix7/mask_clbll_l.db
+ grep -v '<.*>'
+ python3 /big/github/SymbiFlow/prjxray/utils/parsedb.py --strict ./tmp.RNzWhsDeE5 /big/github/SymbiFlow/prjxray/database/artix7/mask_clbll_l.db
Traceback (most recent call last):
  File "/big/github/SymbiFlow/prjxray/utils/parsedb.py", line 53, in <module>
    main()
  File "/big/github/SymbiFlow/prjxray/utils/parsedb.py", line 49, in main
    run(args.fin, args.fout, strict=args.strict, verbose=args.verbose)
  File "/big/github/SymbiFlow/prjxray/utils/parsedb.py", line 14, in run
    tag, bits, mode = util.parse_db_line(line)
  File "/big/github/SymbiFlow/prjxray/prjxray/util.py", line 82, in parse_db_line
    tag), "Invalid tag name: %s, line: %s" % (tag, line)
AssertionError: Invalid tag name: bit, line: bit 00_00
Makefile:15: recipe for target 'pushdb' failed
make[2]: *** [pushdb] Error 1
make[2]: Leaving directory '/big/github/SymbiFlow/prjxray/fuzzers/050-intpips'
Makefile:28: recipe for target 'run' failed
make[1]: *** [run] Error 2
make[1]: Leaving directory '/big/github/SymbiFlow/prjxray/fuzzers/050-intpips'
Makefile:23: recipe for target '050-intpips/run.ok' failed
make: *** [050-intpips/run.ok] Error 2
```

**Comment by mcmasterg** [comment]
this will probably get fixed by https://github.com/SymbiFlow/prjxray/pull/263

**Comment by mithro** [comment]
I believe this is fixed, right?
