### ISSUE TITLE
bram duplicate tag

### ISSUE THREAD

**Issue by JohnDMcMaster** [SymbiFlow/prjxray#382]
Found on quick build, but I'm not sure its quick specific

```
mcmaster@cluster:/mnt/m10_2/buffer/prjxray.2/fuzzers/026-bram-data$ make pushdb
bash /mnt/m10_2/buffer/prjxray.2/utils/mergedb.sh bram_l build/segbits_bramx.db
+ test 2 = 2
+ test -e build/segbits_bramx.db
++ mktemp -p .
+ tmp1=./tmp.J3AMO7Flln
++ mktemp -p .
+ tmp2=./tmp.kdhMtaPrT2
+ trap finish EXIT
+ db=/mnt/m10_2/buffer/prjxray.2/database/artix7/segbits_bram_l.db
+ '[' -f /mnt/m10_2/buffer/prjxray.2/database/artix7/segbits_bram_l.db ']'
+ python3 /mnt/m10_2/buffer/prjxray.2/utils/parsedb.py --strict /mnt/m10_2/buffer/prjxray.2/database/artix7/segbits_bram_l.db
+ python3 /mnt/m10_2/buffer/prjxray.2/utils/parsedb.py --strict build/segbits_bramx.db
+ case "$1" in
+ sed -e 's/^BRAM\./BRAM_L./'
+ touch /mnt/m10_2/buffer/prjxray.2/database/artix7/segbits_bram_l.db
+ sort -u ./tmp.J3AMO7Flln /mnt/m10_2/buffer/prjxray.2/database/artix7/segbits_bram_l.db
+ grep -v '<.*>'
+ python3 /mnt/m10_2/buffer/prjxray.2/utils/parsedb.py --strict ./tmp.kdhMtaPrT2 /mnt/m10_2/buffer/prjxray.2/database/artix7/segbits_bram_l.db
Traceback (most recent call last):
  File "/mnt/m10_2/buffer/prjxray.2/utils/parsedb.py", line 61, in <module>
    main()
  File "/mnt/m10_2/buffer/prjxray.2/utils/parsedb.py", line 57, in main
    run(args.fin, args.fout, strict=args.strict, verbose=args.verbose)
  File "/mnt/m10_2/buffer/prjxray.2/utils/parsedb.py", line 27, in run
    bits, tag, bitss[bits])
AssertionError: strict: got duplicate bits frozenset({'27_319'}): BRAM_L.RAMB36.INIT[6912] BRAM_L.RAMB18_Y1.INIT_B[2]
+ finish
+ echo 'Cleaning up temp files'
Cleaning up temp files
+ rm -f ./tmp.J3AMO7Flln
+ rm -f ./tmp.kdhMtaPrT2
../bram.mk:22: recipe for target 'pushdb' failed
make: *** [pushdb] Error 1
```

**Comment by JohnDMcMaster** [comment]
bram data is not in the main memory area. Regression from making bram.mk
