### ISSUE TITLE
intpips failure

### ISSUE THREAD

**Issue by JohnDMcMaster** [SymbiFlow/prjxray#383]
```
mcmaster@cluster:/mnt/m10_2/buffer/prjxray/fuzzers$ time make -j $(nproc)
...
make[2]: Leaving directory '/mnt/m10_2/buffer/prjxray/fuzzers/050-intpips'
+ python3 /mnt/m10_2/buffer/prjxray/fuzzers/int_loop_check.py --max-iters 12 --stable-iters 2
   1 57fef550   7244 lines      1 stable
   2 a59c511c    776 lines      1 stable
   3 b4b06fc2    613 lines      1 stable
   4 68fe99cd    553 lines      1 stable
   5 6e4f2e44    532 lines      1 stable
   6 2bedea7d    522 lines      1 stable
   7 36f77ad5    512 lines      1 stable
   8 10e39d1c    504 lines      1 stable
   9 f5a330b8    501 lines      1 stable
  10 0d922037    498 lines      1 stable
  11 88efea8e    497 lines      1 stable
  12 028c115c    493 lines      1 stable
Complete: reached max iters (want 12, got 12)
+ break
+ true
+ make pushdb
make[2]: Entering directory '/mnt/m10_2/buffer/prjxray/fuzzers/050-intpips'
bash /mnt/m10_2/buffer/prjxray/utils/mergedb.sh int_l build/segbits_int_l.db
+ test 2 = 2
+ test -e build/segbits_int_l.db
++ mktemp -p .
+ tmp1=./tmp.jc9XBDF3uQ
++ mktemp -p .
+ tmp2=./tmp.b3LBqIZI6S
+ trap finish EXIT
+ db=/mnt/m10_2/buffer/prjxray/database/artix7/segbits_int_l.db
+ '[' -f /mnt/m10_2/buffer/prjxray/database/artix7/segbits_int_l.db ']'
+ python3 /mnt/m10_2/buffer/prjxray/utils/parsedb.py --strict build/segbits_int_l.db
Traceback (most recent call last):
  File "/mnt/m10_2/buffer/prjxray/utils/parsedb.py", line 61, in <module>
    main()
  File "/mnt/m10_2/buffer/prjxray/utils/parsedb.py", line 57, in main
    run(args.fin, args.fout, strict=args.strict, verbose=args.verbose)
  File "/mnt/m10_2/buffer/prjxray/utils/parsedb.py", line 27, in run
    bits, tag, bitss[bits])
AssertionError: strict: got duplicate bits frozenset(): INT.IMUX_L13.VCC_WIRE INT.IMUX_L12.VCC_WIRE
+ finish
+ echo 'Cleaning up temp files'
Cleaning up temp files
+ rm -f ./tmp.jc9XBDF3uQ
+ rm -f ./tmp.b3LBqIZI6S
Makefile:39: recipe for target 'pushdb' failed
make[2]: *** [pushdb] Error 1
make[2]: Leaving directory '/mnt/m10_2/buffer/prjxray/fuzzers/050-intpips'
Makefile:69: recipe for target 'run' failed
make[1]: *** [run] Error 2
make[1]: Leaving directory '/mnt/m10_2/buffer/prjxray/fuzzers/050-intpips'
Makefile:36: recipe for target '050-intpips/run.ok' failed
make: *** [050-intpips/run.ok] Error 2

real    475m4.611s
user    7113m38.424s
sys     323m1.788s
```

**Comment by JohnDMcMaster** [comment]
These entries are empty. Weird. Maybe we should filter them out?

**Comment by JohnDMcMaster** [comment]
In general IMUX VCC wires don't seem to solve correctly. Maybe we should filter them out

```
$ grep -Hni vcc build/*.db
build/segbits_int_l.db:22:INT.BYP_ALT0.VCC_WIRE 31_02 31_26 31_37 31_62
build/segbits_int_l.db:47:INT.BYP_ALT1.VCC_WIRE 30_02 30_25 30_37 30_60
build/segbits_int_l.db:811:INT.IMUX_L12.VCC_WIRE
build/segbits_int_l.db:836:INT.IMUX_L13.VCC_WIRE
build/segbits_int_l.db:1383:INT.IMUX_L34.VCC_WIRE
build/segbits_int_l.db:1408:INT.IMUX_L35.VCC_WIRE
build/segbits_int_l.db:1529:INT.IMUX_L4.VCC_WIRE
build/segbits_int_l.db:1601:INT.IMUX_L42.VCC_WIRE
build/segbits_int_l.db:1625:INT.IMUX_L43.VCC_WIRE
build/segbits_int_l.db:1744:INT.IMUX_L5.VCC_WIRE
build/segbits_int_r.db:22:INT.BYP_ALT0.VCC_WIRE 31_02 31_26 31_37 31_62
build/segbits_int_r.db:47:INT.BYP_ALT1.VCC_WIRE 30_02 30_25 30_37 30_60
build/segbits_int_r.db:813:INT.IMUX12.VCC_WIRE
build/segbits_int_r.db:838:INT.IMUX13.VCC_WIRE
build/segbits_int_r.db:1385:INT.IMUX34.VCC_WIRE
build/segbits_int_r.db:1410:INT.IMUX35.VCC_WIRE
build/segbits_int_r.db:1531:INT.IMUX4.VCC_WIRE
build/segbits_int_r.db:1603:INT.IMUX42.VCC_WIRE
build/segbits_int_r.db:1627:INT.IMUX43.VCC_WIRE
```

**Comment by JohnDMcMaster** [comment]
VCC wires are supposed to be dropped:
050-intpips/Makefile:12:MAKETODO_FLAGS=--re ".*" --not-endswith ".VCC_WIRE"
I'm guessing this mechanism is not working

**Comment by JohnDMcMaster** [comment]
They aren't appearing in the TODO list, but generate.py chomps whatever it finds. It has a few excludes, but it needs to be expanded I guess
```
        if pnum == 1 or pdir == 0 or \
                re.match(r"^(L[HV]B?|G?CLK)(_L)?(_B)?[0-9]", src) or \
                re.match(r"^(L[HV]B?|G?CLK)(_L)?(_B)?[0-9]", dst) or \
                re.match(r"^(CTRL|GFAN)(_L)?[0-9]", dst):
            ignpip.add(pip)
```
