### ISSUE TITLE
rempips merging in undersolved entries

### ISSUE THREAD

**Issue by JohnDMcMaster** [SymbiFlow/prjxray#389]
Summary:
* intpips merges in at the end, but other int_loop fuzzers merge per iteration. This means even though we continue to create segbit files, they aren't effectively used (as demonstrated here). However, because we merge early and then check for duplicates as we go, we detect the changed entry
* Related ticket: https://github.com/SymbiFlow/prjxray/issues/318
* Default int_loop is "-m 10 -M 20" while intpips uses "-m 15 -M 45". Looks like if we unify to the stricter settings, this issue will probably solve

```
+ python3 /mnt/m10_2/buffer/prjxray/utils/parsedb.py --strict ./tmp.lyEPt6yA7B /mnt/m10_2/buffer/prjxray/database/artix7/segbits_int_r.db
Original line: INT_R.FAN_ALT1.GFAN1 !00_18 !00_19 !01_13 !22_48 !23_48 !24_48 00_14 00_17 21_48 25_48
New line: INT_R.FAN_ALT1.GFAN1 !22_48 !23_48 !24_48 21_48 25_48
Traceback (most recent call last):
  File "/mnt/m10_2/buffer/prjxray/utils/parsedb.py", line 61, in <module>
    main()
  File "/mnt/m10_2/buffer/prjxray/utils/parsedb.py", line 57, in main
    run(args.fin, args.fout, strict=args.strict, verbose=args.verbose)
  File "/mnt/m10_2/buffer/prjxray/utils/parsedb.py", line 25, in run
    assert 0, "strict: got duplicate tag %s" % (tag, )
AssertionError: strict: got duplicate tag INT_R.FAN_ALT1.GFAN1
+ finish
+ echo 'Cleaning up temp files'
Cleaning up temp files
+ rm -f ./tmp.9wkSMxDSts
+ rm -f ./tmp.lyEPt6yA7B
../int_loop.mk:44: recipe for target 'pushdb' failed
make[2]: *** [pushdb] Error 1
make[2]: Leaving directory '/mnt/m10_2/buffer/prjxray/fuzzers/056-rempips'
../int_loop.mk:74: recipe for target 'run' failed
make[1]: *** [run] Error 2
make[1]: Leaving directory '/mnt/m10_2/buffer/prjxray/fuzzers/056-rempips'
Makefile:42: recipe for target '056-rempips/run.ok' failed
make: *** [056-rempips/run.ok] Error 2
```

```
mcmaster@cluster:/mnt/m10_2/buffer/prjxray/fuzzers/056-rempips$ grep -Hn FAN_ALT1.GFAN1 build/*/segbits_int_r.db |sort
build/10/segbits_int_r.db:6:INT.FAN_ALT1.GFAN1 00_14 00_17 21_48 25_48
build/11/segbits_int_r.db:6:INT.FAN_ALT1.GFAN1 00_14 00_17 21_48 25_48
build/12/segbits_int_r.db:6:INT.FAN_ALT1.GFAN1 00_14 00_17 21_48 25_48
build/13/segbits_int_r.db:7:INT.FAN_ALT1.GFAN1 00_14 00_17 21_48 25_48
build/14/segbits_int_r.db:8:INT.FAN_ALT1.GFAN1 00_14 00_17 21_48 25_48
build/15/segbits_int_r.db:8:INT.FAN_ALT1.GFAN1 00_14 00_17 21_48 25_48
build/16/segbits_int_r.db:8:INT.FAN_ALT1.GFAN1 21_48 25_48
```

**Comment by JohnDMcMaster** [comment]
This was "fixed" but caused https://github.com/SymbiFlow/prjxray/issues/418
