### ISSUE TITLE
058-hclkpips generate failure

### ISSUE THREAD

**Issue by JohnDMcMaster** [SymbiFlow/prjxray#392]
````
mcmaster@cluster:/mnt/m10_2/buffer/prjxray/fuzzers/058-hclkpips/build/specimen_001$ VERBOSE=Y python3 /mnt/m10_2/buffer/prjxray/fuzzers/058-hclkpips/generate.py design_0 design_100 ..._96 design_97 design_98 design_99 design_9
Preload all tags.
Processing design_0.
Loading bits from design_0.bits.
Loaded bits: 192 bits in 7 base frames
Indexing sites
Sites indexed
Compiling segment data.
Used 0 / 204 tags
Tag sites: 0
Tag tiles: 204
Used 0 sites
Grid DB had 112 tile types
Traceback (most recent call last):
  File "/mnt/m10_2/buffer/prjxray/fuzzers/058-hclkpips/generate.py", line 50, in <module>
    segmk.compile()
  File "/mnt/m10_2/buffer/prjxray/prjxray/segmaker.py", line 376, in compile
    len(tags_used), ntags)
AssertionError: Unused tags, 0 used out of 204
```

**Comment by JohnDMcMaster** [comment]
Added a better message

```
Compiling segment data.
Traceback (most recent call last):
  File "/mnt/m10_2/buffer/prjxray/fuzzers/058-hclkpips/generate.py", line 50, in <module>
    segmk.compile()
  File "/mnt/m10_2/buffer/prjxray/prjxray/segmaker.py", line 342, in compile
    assert this_tile_tags == 0, "Tile %s does not have bitstream info but %s tags" % (tilename, this_tile_tags)
AssertionError: Tile HCLK_L_X4Y130 does not have bitstream info but 204 tags
```

Possibly a tilegrid regression

**Comment by JohnDMcMaster** [comment]
DB git master does not have HCLK db, but fcb76b4ac952140a907fca67dc1103a29dfbc2d2 does (last commit when we did a sprint last year). I didn't check in between. So probably need to look at tilegrid and figure out what happened.

**Comment by JohnDMcMaster** [comment]
Upon closer examination, we do in fact have HCLK for *most* tiles in the ROI, just not this one. HCLK definitions are auto-magically created by propagating from LUT base addresses. However, there is no LUT in this column to propagate from.

I'll add a workaround for now

**Comment by JohnDMcMaster** [comment]
Another note about current HCLK code: it only works on a single tile per tile type. Most other fuzzers work on a random assortment of tiles. We should probably re-write this fuzzer to be more generic to ensure the bits really are set the same across tiles.

**Comment by JohnDMcMaster** [comment]
We have a workaround for now. Re-open or open a new issue if becomes relevant again
