### ISSUE TITLE
rempips duplicate tag

### ISSUE THREAD

**Issue by JohnDMcMaster** [SymbiFlow/prjxray#399]
Seems pretty rare these days. In leiu of adding stricter matching, I'm thinking maybe we just warn and/or add some logic to de-conflict. For example, if one entry is a subset of the other, we can probably guess the smaller entry is correct.

Another mitigation would be to have rempips iteratively push to a local db.  That way if it got better data later, it would just overwrite it. Does it need to do a push per iteration? Maybe that can just be eliminated

```
bash /mnt/m10_2/buffer/prjxray.2/utils/mergedb.sh int_l build/segbits_int_l.db
+ test 2 = 2
+ test -e build/segbits_int_l.db
++ mktemp -p .
+ tmp1=./tmp.GevoblSPLD
++ mktemp -p .
+ tmp2=./tmp.ne2KftRtQ6
+ trap finish EXIT
+ db=/mnt/m10_2/buffer/prjxray.2/database/artix7/segbits_int_l.db
+ '[' -f /mnt/m10_2/buffer/prjxray.2/database/artix7/segbits_int_l.db ']'
+ python3 /mnt/m10_2/buffer/prjxray.2/utils/parsedb.py --strict /mnt/m10_2/buffer/prjxray.2/database/artix7/segbits_int_l.db
+ python3 /mnt/m10_2/buffer/prjxray.2/utils/parsedb.py --strict build/segbits_int_l.db
+ case "$1" in
+ sed -e 's/^INT\./INT_L./'
+ touch /mnt/m10_2/buffer/prjxray.2/database/artix7/segbits_int_l.db
+ sort -u ./tmp.GevoblSPLD /mnt/m10_2/buffer/prjxray.2/database/artix7/segbits_int_l.db
+ grep -v '<.*>'
+ python3 /mnt/m10_2/buffer/prjxray.2/utils/parsedb.py --strict ./tmp.ne2KftRtQ6 /mnt/m10_2/buffer/prjxray.2/database/artix7/segbits_int_l.db
Original line: INT_L.FAN_ALT1.GFAN1 !00_18 !00_19 !01_13 !22_48 !23_48 !24_48 00_14 00_17 21_48 25_48
New line: INT_L.FAN_ALT1.GFAN1 !22_48 !23_48 !24_48 21_48 25_48
Traceback (most recent call last):
  File "/mnt/m10_2/buffer/prjxray.2/utils/parsedb.py", line 61, in <module>
    main()
  File "/mnt/m10_2/buffer/prjxray.2/utils/parsedb.py", line 57, in main
    run(args.fin, args.fout, strict=args.strict, verbose=args.verbose)
  File "/mnt/m10_2/buffer/prjxray.2/utils/parsedb.py", line 25, in run
    assert 0, "strict: got duplicate tag %s" % (tag, )
AssertionError: strict: got duplicate tag INT_L.FAN_ALT1.GFAN1
+ finish
+ echo 'Cleaning up temp files'
Cleaning up temp files
+ rm -f ./tmp.GevoblSPLD
+ rm -f ./tmp.ne2KftRtQ6
../int_loop.mk:44: recipe for target 'pushdb' failed
make[2]: *** [pushdb] Error 1
make[2]: Leaving directory '/mnt/m10_2/buffer/prjxray.2/fuzzers/056-rempips'
../int_loop.mk:74: recipe for target 'run' failed
make[1]: *** [run] Error 2
make[1]: Leaving directory '/mnt/m10_2/buffer/prjxray.2/fuzzers/056-rempips'
Makefile:42: recipe for target '056-rempips/run.ok' failed
make: *** [056-rempips/run.ok] Error 2
```

**Comment by JohnDMcMaster** [comment]
rempips now iterates locally. I believe that fixed this
