### ISSUE TITLE
segprint -b broken

### ISSUE THREAD

**Issue by mcmasterg** [SymbiFlow/prjxray#443]
Tried this in the bram-config directory

```
$ $XRAY_SEGPRINT -z -b -d build/specimen_001/design.bits 
Traceback (most recent call last):
  File "/home/mcmaster/prjxray/utils/segprint.py", line 472, in <module>
    main()
  File "/home/mcmaster/prjxray/utils/segprint.py", line 468, in main
    args.D, args.verbose)
  File "/home/mcmaster/prjxray/utils/segprint.py", line 412, in run
    print_unknown_bits(segments, bitdata)
  File "/home/mcmaster/prjxray/utils/segprint.py", line 111, in print_unknown_bits
    block["baseaddr"][1] + block["words"]):
TypeError: Can't convert 'int' object to str implicitly
```

**Comment by mcmasterg** [comment]
Sounds like this is fixed
