### ISSUE TITLE
Fuzzer 013 Duplicate Tag

### ISSUE THREAD

**Issue by natsfr** [SymbiFlow/prjxray#532]
While trying to run all the Fuzzer on an Artix 7 target I got a duplicate tag error on Fuzzer 013
```
make[2]: Entering directory '/home/nats/project/symbiflow/prjxray/fuzzers/013-clb-ncy0'
bash /home/nats/project/symbiflow/prjxray/utils/mergedb.sh clbll_l build/segbits_clbx.db
+ test 2 = 2
+ test -e build/segbits_clbx.db
++ mktemp -p .
+ tmp1=./tmp.ierxhivJb0
++ mktemp -p .
+ tmp2=./tmp.1uX2sknDxY
+ trap finish EXIT
+ db=/home/nats/project/symbiflow/prjxray/database/artix7/segbits_clbll_l.db
+ '[' -f /home/nats/project/symbiflow/prjxray/database/artix7/segbits_clbll_l.db ']'
+ python3 /home/nats/project/symbiflow/prjxray/utils/parsedb.py --strict /home/nats/project/symbiflow/prjxray/database/artix7/segbits_clbll_l.db
+ python3 /home/nats/project/symbiflow/prjxray/utils/parsedb.py --strict build/segbits_clbx.db
+ ismask=false
+ case "$1" in
+ sed -e 's/^CLB\.SLICE_X0\./CLBLL_L.SLICEL_X0./' -e 's/^CLB\.SLICE_X1\./CLBLL_L.SLICEL_X1./'
+ touch /home/nats/project/symbiflow/prjxray/database/artix7/segbits_clbll_l.db
+ false
+ python3 /home/nats/project/symbiflow/prjxray/utils/mergedb.py --out ./tmp.1uX2sknDxY /home/nats/project/symbiflow/prjxray/database/artix7/segbits_clbll_l.db ./tmp.ierxhivJb0
WARNING: got duplicate tag CLBLL_L.SLICEL_X1.CARRY4.ACY0
  Orig line: CLBLL_L.SLICEL_X1.CARRY4.ACY0 31_01 31_04 31_14 31_15
  New line : CLBLL_L.SLICEL_X1.CARRY4.ACY0 31_14
Traceback (most recent call last):
  File "/home/nats/project/symbiflow/prjxray/utils/mergedb.py", line 64, in <module>
    main()
  File "/home/nats/project/symbiflow/prjxray/utils/mergedb.py", line 60, in main
    verbose=args.verbose)
  File "/home/nats/project/symbiflow/prjxray/utils/mergedb.py", line 28, in run
    assert not strict, "strict: got duplicate tag"
AssertionError: strict: got duplicate tag
+ finish
+ echo 'Cleaning up temp files'
Cleaning up temp files
+ rm -f ./tmp.ierxhivJb0
+ rm -f ./tmp.1uX2sknDxY
../clb.mk:31: recipe for target 'pushdb' failed
make[2]: *** [pushdb] Error 1
make[2]: Leaving directory '/home/nats/project/symbiflow/prjxray/fuzzers/013-clb-ncy0'
../fuzzer.mk:12: recipe for target 'run' failed
make[1]: *** [run] Error 2
make[1]: Leaving directory '/home/nats/project/symbiflow/prjxray/fuzzers/013-clb-ncy0'
Makefile:30: recipe for target '013-clb-ncy0/run.ok' failed
make: *** [013-clb-ncy0/run.ok] Error 2
```
Copying @kgugala

**Comment by natsfr** [comment]
An explicit "make clean" in the prjxray/database/ cleared the problem. Maybe we should look at how dependencies are ordered.
