### ISSUE TITLE
BRAM tests in arch-defs fails on Artix7

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/prjxray#571]
With the latest db (commit 44ce9a46e84b8d3a354e1c3c7626465742598b15) the BRAM tests in the xc7/tests folder of symbiflow-arch-defs repo fails with the following message:

```
Traceback (most recent call last):
  File "/home/build/symbiflow-arch-defs/third_party/prjxray/prjxray/fasm_assembler.py", line 133, in enable_feature
    for bit in segbits.feature_to_bits(db_k, address):
  File "/home/build/symbiflow-arch-defs/third_party/prjxray/prjxray/tile_segbits.py", line 141, in feature_to_bits
    for bit in self.segbits[self.feature_addresses[feature][address]]:
KeyError: 'BRAM_L.BRAM_LOGIC_OUTS_B10_3.BRAM_RAMB18_DOADO3'
```

**Comment by litghost** [comment]
This is a known issue, #477
