### ISSUE TITLE
Collision between INT_L_X24Y112.INT_L.FAN_ALT7.GFAN1 and CLBLL_L_X24Y112.CLBLL_L.SLICEL_X0.CEUSEDMUX

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#611]
Latest build in the artix7 has the following issue;
```
Checking database/artix7
============================
Checking individual .db...
segbits_*.db: 14 okay
mask_*.db: 12 okay
Checking aggregate dir...
ERROR: 1 collisions
  00020c01_025_07: had INT_L_X24Y112.INT_L.FAN_ALT7.GFAN1, got CLBLL_L_X24Y112.CLBLL_L.SLICEL_X0.CEUSEDMUX
Traceback (most recent call last):
  File "utils/checkdb.py", line 136, in <module>
    main()
  File "utils/checkdb.py", line 132, in main
    run(args.db_root, strict=args.strict, verbose=args.verbose)
  File "utils/checkdb.py", line 118, in run
    check_tile_overlap(db, db_root, strict=strict, verbose=verbose)
  File "utils/checkdb.py", line 94, in check_tile_overlap
    raise ValueError("%s collisions" % len(collisions))
ValueError: 1 collisions
```

**Comment by litghost** [comment]
Is this just another duplicate of #567?

**Comment by mithro** [comment]
Seem like it might be...

**Comment by litghost** [comment]
If CLBLL_L.SLICEL_X0.CEUSEDMUX is same as before, then this is just a dup of #567

**Comment by acomodi** [comment]
As said in https://github.com/SymbiFlow/prjxray/issues/567, would it be worth re-testing with 054-pips-gfan fuzzer and see if the problem persists?
