### ISSUE TITLE
AssertionError: Tile INT_L_X24Y90 does not have bitstream info but 4483 tags

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#618]
```
2019-02-07T03:42:43.913561 - 050-pip-seed             - 14m27s: + python3 /tmpfs/src/github/symbiflow-prjxray-continuous-db-kintex7/fuzzers/050-pip-seed/generate.py
2019-02-07T03:42:43.913561 - 050-pip-seed             - 14m27s: Traceback (most recent call last):
2019-02-07T03:42:43.913561 - 050-pip-seed             - 14m27s:   File "/tmpfs/src/github/symbiflow-prjxray-continuous-db-kintex7/fuzzers/050-pip-seed/generate.py", line 68, in <module>
2019-02-07T03:42:43.913561 - 050-pip-seed             - 14m27s:     segmk.compile(bitfilter=get_bitfilter(os.getenv('XRAY_DATABASE'), 'INT'))
2019-02-07T03:42:43.913561 - 050-pip-seed             - 14m27s:   File "/tmpfs/src/github/symbiflow-prjxray-continuous-db-kintex7/prjxray/segmaker.py", line 348, in compile
2019-02-07T03:42:43.913561 - 050-pip-seed             - 14m27s:     tilename, this_tile_tags)
2019-02-07T03:42:43.913561 - 050-pip-seed             - 14m27s: AssertionError: Tile INT_L_X24Y90 does not have bitstream info but 4483 tags
```

**Comment by litghost** [comment]
Which part is this?

**Comment by litghost** [comment]
If this is Kintex7, this could be due to #566

**Comment by mithro** [comment]
Give https://source.cloud.google.com/results/invocations/19862a66-f746-45ad-97e8-b3f9140f291d/targets a look...

**Comment by litghost** [comment]
Ya, that's a Kintex build,

**Comment by litghost** [comment]
Looks like I'll need to completely solve for INT tiles (or filter them):

2019-02-07T19:49:19.566035 - 051-pip-imuxlout-bypalts - 14m14s: AssertionError: Tile INT_R_X25Y24 does not have bitstream info but 33 tags
2019-02-07T19:49:19.566035 - 051-pip-imuxlout-bypalts - 14m14s: make[3]: *** [generate.ok] Error 1

Working on it.
