### ISSUE TITLE
051-pip-imuxlout-bypalts fuzzer unstable for Zynq7

### ISSUE THREAD

**Issue by tmichalak** [SymbiFlow/prjxray#811]
@kgugala noticed in one of the CI runs in PR #706 the following issue:
<pre>
37405 2019-04-29T03:14:54.522857 - 051-pip-imuxlout-bypalts - 1h06m: + python3 /tmpfs/src/github/symbiflow-prjxray-presubmit-db-zynq7/utils/mergedb.py --out ./tmp.1x3IZCiDAU /tmpfs/src/github/symbiflow-prjxray-presubmit-db-zynq7/fuzzers/051-pip-imuxlout-bypalts/build/database/zynq7      /segbits_int_r.db ./tmp.OsjfQalpcr^M
37406 2019-04-29T03:14:54.522857 - 051-pip-imuxlout-bypalts - 1h06m: Traceback (most recent call last):^M
37407 2019-04-29T03:14:54.522857 - 051-pip-imuxlout-bypalts - 1h06m:   File "/tmpfs/src/github/symbiflow-prjxray-presubmit-db-zynq7/utils/mergedb.py", line 63, in <module>^M
37408 2019-04-29T03:14:54.522857 - 051-pip-imuxlout-bypalts - 1h06m:     main()^M
37409 2019-04-29T03:14:54.522857 - 051-pip-imuxlout-bypalts - 1h06m:   File "/tmpfs/src/github/symbiflow-prjxray-presubmit-db-zynq7/utils/mergedb.py", line 59, in main^M
37410 2019-04-29T03:14:54.522857 - 051-pip-imuxlout-bypalts - 1h06m:     verbose=args.verbose)^M
37411 2019-04-29T03:14:54.522857 - 051-pip-imuxlout-bypalts - 1h06m:   File "/tmpfs/src/github/symbiflow-prjxray-presubmit-db-zynq7/utils/mergedb.py", line 27, in run^M
37412 2019-04-29T03:14:54.522857 - 051-pip-imuxlout-bypalts - 1h06m:     assert not strict, "strict: got duplicate tag"^M
37413 2019-04-29T03:14:54.522857 - 051-pip-imuxlout-bypalts - 1h06m: AssertionError: strict: got duplicate tag^M
</pre>
This problem hasn't been addressed so far as it hadn't been spotted before.

**Comment by tmichalak** [comment]
I haven't seen this fuzzer fail for a while now. Hence closing.
